import dataclasses


@dataclasses.dataclass
class FieldLabel:
    label: str
    unit: str = None


VEHICLES_TO_SCRAPE = [
    "https://ev-database.org/imp/car/2016/Audi-Q4-Sportback-e-tron-45",
    "https://ev-database.org/imp/car/1991/Tesla-Model-3",
    "https://ev-database.org/imp/car/1717/Hyundai-IONIQ-6-Standard-Range-2WD",
    "https://ev-database.org/imp/car/1992/Tesla-Model-3-Long-Range-Dual-Motor",
    "https://ev-database.org/imp/car/1718/Hyundai-IONIQ-6-Long-Range-2WD",
    "https://ev-database.org/imp/car/1252/BMW-i4-eDrive40",
    "https://ev-database.org/imp/car/1785/BMW-i4-eDrive35",
    "https://ev-database.org/imp/car/1997/Mini-Cooper-E",
    "https://ev-database.org/imp/car/2028/Volkswagen-ID4-Pro",
    "https://ev-database.org/imp/car/2186/Tesla-Model-Y-Long-Range-RWD",
    "https://ev-database.org/imp/car/1743/Tesla-Model-Y",
    "https://ev-database.org/imp/car/1974/Tesla-Model-Y",
    "https://ev-database.org/imp/car/1817/Polestar-2-Standard-Range-Single-Motor",
    "https://ev-database.org/imp/car/1404/Tesla-Model-S-Dual-Motor",
    "https://ev-database.org/imp/car/1719/Hyundai-IONIQ-6-Long-Range-AWD",
    "https://ev-database.org/imp/car/1829/Hyundai-Kona-Electric-48-kWh",
    "https://ev-database.org/imp/car/1666/Kia-Niro-EV",
    "https://ev-database.org/imp/car/1988/Mercedes-Benz-EQB-250plus",
    "https://ev-database.org/imp/car/1984/Mercedes-Benz-EQA-250",
    "https://ev-database.org/imp/car/1985/Mercedes-Benz-EQA-250plus",
    "https://ev-database.org/imp/car/1818/Polestar-2-Long-Range-Single-Motor",
    "https://ev-database.org/imp/car/1830/Hyundai-Kona-Electric-65-kWh",
    "https://ev-database.org/imp/car/1897/Mercedes-Benz-EQE-300",
    "https://ev-database.org/imp/car/1619/Tesla-Model-Y-Long-Range-Dual-Motor",
    "https://ev-database.org/imp/car/1820/Polestar-2-Long-Range-Performance",
    "https://ev-database.org/imp/car/1819/Polestar-2-Long-Range-Dual-Motor",
    "https://ev-database.org/imp/car/1480/Kia-EV6-Standard-Range-2WD",
    "https://ev-database.org/imp/car/1910/Volvo-EX30-Single-Motor-ER",
    "https://ev-database.org/imp/car/1183/Tesla-Model-Y-Performance",
    "https://ev-database.org/imp/car/1481/Kia-EV6-Long-Range-2WD",
    "https://ev-database.org/imp/car/1911/Volvo-EX30-Twin-Motor-Performance",
    "https://ev-database.org/imp/car/1476/Hyundai-IONIQ-5-Standard-Range-2WD",
    "https://ev-database.org/imp/car/1482/Kia-EV6-Long-Range-AWD",
    "https://ev-database.org/imp/car/2013/Audi-Q4-e-tron-45",
    "https://ev-database.org/imp/car/2018/Audi-Q4-Sportback-e-tron-55-quattro",
    "https://ev-database.org/imp/car/2035/Ford-Mustang-Mach-E-ER-RWD",
    "https://ev-database.org/imp/car/2124/Volvo-EC40-Single-Motor-ER",
    "https://ev-database.org/imp/car/1943/Lexus-UX-300e",
    "https://ev-database.org/imp/car/1564/Toyota-bZ4X-FWD",
    "https://ev-database.org/imp/car/2123/Volvo-EC40-Single-Motor",
    "https://ev-database.org/imp/car/1535/BMW-iX3",
    "https://ev-database.org/imp/car/1841/Polestar-4-Long-Range-Single-Motor",
    "https://ev-database.org/imp/car/1662/Hyundai-IONIQ-5-Long-Range-2WD",
    "https://ev-database.org/imp/car/1990/Mercedes-Benz-EQB-350-4MATIC",
    "https://ev-database.org/imp/car/1989/Mercedes-Benz-EQB-300-4MATIC",
    "https://ev-database.org/imp/car/2034/Ford-Mustang-Mach-E-SR-RWD",
    "https://ev-database.org/imp/car/1987/Mercedes-Benz-EQA-350-4MATIC",
    "https://ev-database.org/imp/car/1986/Mercedes-Benz-EQA-300-4MATIC",
    "https://ev-database.org/imp/car/2120/Volvo-EX40-Single-Motor",
    "https://ev-database.org/imp/car/2015/Audi-Q4-e-tron-55-quattro",
    "https://ev-database.org/imp/car/2014/Audi-Q4-e-tron-45-quattro",
    "https://ev-database.org/imp/car/1663/Hyundai-IONIQ-5-Long-Range-AWD",
    "https://ev-database.org/imp/car/2137/Volvo-EC40-Twin-Motor",
    "https://ev-database.org/imp/car/2125/Volvo-EC40-Twin-Motor-Performance",
    "https://ev-database.org/imp/car/1567/Subaru-Solterra-AWD",
    "https://ev-database.org/imp/car/2121/Volvo-EX40-Single-Motor-ER",
    "https://ev-database.org/imp/car/1565/Toyota-bZ4X-AWD",
    "https://ev-database.org/imp/car/1842/Polestar-4-Long-Range-Dual-Motor",
    "https://ev-database.org/imp/car/2044/Hyundai-IONIQ-5-N",
    "https://ev-database.org/imp/car/2146/Audi-Q6-e-tron-quattro",
    "https://ev-database.org/imp/car/2122/Volvo-EX40-Twin-Motor-Performance",
    "https://ev-database.org/imp/car/1471/Kia-EV6-GT",
    "https://ev-database.org/imp/car/2136/Volvo-EX40-Twin-Motor",
    "https://ev-database.org/imp/car/1769/Audi-Q8-e-tron-50-quattro",
]

FIELD_LABEL_LIST = [
    FieldLabel("Warranty Period", "years"),
    FieldLabel("City - Mild Weather*", "mi"),
    FieldLabel("Highway - Mild Weather*", "mi"),
    FieldLabel("Combined - Mild Weather*", "mi"),
    FieldLabel("Electric Range", "mi"),
    FieldLabel("Drive"),
    # FieldLabel("Useable Capacity", "kWh"),
    # FieldLabel("Charge Port"),
    FieldLabel("Charge Power", "kW"),
    FieldLabel("Charge Time", "min"),
    FieldLabel("Charge Speed", "mph"),
    # FieldLabel("Fastcharge Port"),
    FieldLabel("Fastcharge Power \(max\)", "kW DC"),
    # FieldLabel("Fastcharge Power \(10-80%\)", "kW DC"),
    FieldLabel("Fastcharge Time", "min"),
    FieldLabel("V2L Supported"),
    FieldLabel("V2H via AC Supported"),
    # FieldLabel("V2H via DC Supported"),
    FieldLabel("V2G via AC Supported"),
    # FieldLabel("V2G via DC Supported"),
    FieldLabel("Vehicle Consumption *", "Wh/mi"),
    # "Adult Occupant",
]

NON_SPLITTABLE_FIELDS = ["Warranty Period", "Charge Port", "Charge Time"]
